AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/FormatString:
  EnforcedStyle: percent

Style/StringLiterals:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/PredicateName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Alias:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
